(function(){function list(it
/**/) {
var out='<!DOCTYPE html><html lang=\'pt-BR\'> <head> undefined <title>Lista de Produtos | Netshoes</title> </head> <body> <div class="container-fluid"> <div class="container"> <div class="row"> <div class="col-md-4"> </div> <div class="col-md-4" > <div class="input-group"> <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3"> <span class="input-group-addon" id="basic-addon3"> <a href="#">GO!</a> </span> </div> </div> <div class="col-md-4"> </div> </div></div> <ul id="products"> ';var arr1=it.products;if(arr1){var product,index=-1,l1=arr1.length-1;while(index<l1){product=arr1[index+=1];out+=' <li class="product"> <img src="'+(product.image)+'" style="width: 254px" /> <p class="title">'+(product.name)+'</p> <p class="price"> '+( "R$ " + product.price.formatMoney(2, ",", "."))+' </p></li> ';} } out+=' </ul> <div class="clearfix"></div> <nav> <ul class="pagination"> <li class="'+(it.page - 1 || 'disabled')+'" > <a href="/list?page='+(it.page - 1)+'" aria-label="Anterior"> <span aria-hidden="true">&laquo;</span> </a> </li> <li><a href="/list?page=1">1</a></li> <li><a href="/list?page=2">2</a></li> <li> <a href="/list?page='+(it.page + 1)+'" aria-label="Próximo"> <span aria-hidden="true">&raquo;</span> </a> </li> </ul> </nav> <footer> <div class="row"> <div class="col-md-4"> <h2 class="title">Central de Relacionamento</h2> <p>Preparada para esclarecer suas dúvidas</p> </div> <div class="col-md-4"> <h2 class="title">Promoções</h2> Inscreva-se para receber ofertas e descontos exclusivos <input type="text"/> <a class="btn ns-btn-primary" href="#">OK</a> </div> <div class="col-md-4"> <h2 class="title">Sobre a NETSHOES</h2> <ul id="lista-sobre"> <li><a href="#">Política de Privacidade</a></li> <li><a href="#">Trabalho Conosco</a></li> </ul> </div> </div> <div id="terms"> <p> Copyright © 2000 - 2016 www.netshoes.com.br, TODOS OS DIREITOS RESERVADOS. Todo o conteúdo do site, todas as fotos, imagens, logotipos, marcas, dizeres, som, software, conjunto imagem, layout, <br/> trade dress, aqui veiculados são de propriedade exclusiva da NS2.COM Internet S.A. É vedada qualquer reprodução, total ou parcial, de qualquer elemento de identidade, sem expressa autorização. </p> <p> A violação de qualquer direito mencionado implicará na responsabilização cível e criminal nos termos da Lei. </p> <p> Object Edge | F.biz NS2.Com Internet S/A - CNPJ: 09.339.936/0001-16 Rua Vergueiro, 943 - Liberdade - CEP 01504-001 - São Paulo - SP </p> </div></footer> </div> </body></html>';return out;
}var itself=list, _encodeHTML=(function (doNotSkipEncoded) {
		var encodeHTMLRules = { "&": "&#38;", "<": "&#60;", ">": "&#62;", '"': "&#34;", "'": "&#39;", "/": "&#47;" },
			matchHTML = doNotSkipEncoded ? /[&<>"'\/]/g : /&(?!#?\w+;)|<|>|"|'|\//g;
		return function(code) {
			return code ? code.toString().replace(matchHTML, function(m) {return encodeHTMLRules[m] || m;}) : "";
		};
	}());if(typeof module!=='undefined' && module.exports) module.exports=itself;else if(typeof define==='function')define(function(){return itself;});else {window.render=window.render||{};window.render['list']=itself;}}());