info:
  build:
    description: @project.description@
    name: @project.name@
    artifact: @project.artifactId@
    version: @project.version@
  project: @project.name@
  version: @project.version@

server:
     port: 8081
#     servlet-path: /store

spring:
  application:
    name: @project.name@
  devtools:
    remote:
      secret: store
  data:
    mongodb:
      database: store
      host: localhost
      port: 27017

shell:
  ssh:
    enabled: true
  auth:
    simple:
     user:
       name: store
       password: store

domains:
  access:
    control:
      allow:
        origin: '*'
